// elastic adaptive
export const SET_CURRENT_FONT_SIZE = `SET_CURRENT_FONT_SIZE`
export const SET_USER_DEVICE_TYPE = `SET_USER_DEVICE_TYPE`

// ui
export const TOGGLE_MODAL = `TOGGLE_MODAL`
export const SET_LANG = `SET_LANG`

// selection
export const UPDATE_TABLE_SELECTED_ITEMS = `UPDATE_TABLE_SELECTED_ITEMS`

// waypoints
export const SET_WAYPOINTS_STATUS = `SET_WAYPOINTS_STATUS`
export const SET_ACTIVE_WAYPOINT = `SET_ACTIVE_WAYPOINT`